### ISSUE TITLE
Provide the ability upload models/dataset

### ISSUE THREAD

**Issue by ganisback** [OpenCSGs/csghub-sdk#20]
such as 
dataset.push_to_hub("stevhliu/private_processed_demo", private=True)
or by cli:
csghub upload --repo-type=model  stevhliu/private_processed_demo

**Comment by SeanHH86** [comment]
Do you want to create a new repo or update exist repo after finetune?

**Comment by ganisback** [comment]
sure

**Comment by SeanHH86** [comment]
done
