### ISSUE TITLE
cli need display the saved location when finish donwload

### ISSUE THREAD

**Issue by ganisback** [OpenCSGs/csghub-sdk#24]
(base) xiangzhen@192 starhub-server % csghub-cli download hiveer/dataset112 -t dataset -e http://localhost:8080
Downloading .gitattributes: 100%|██████████████████████████████████████████████████████████████████████████████| 2.25k/2.25k [00:00<00:00, 15.0MB/s]
Downloading README.md: 100%|██████████████████████████████████████████████████████████████████████████████████████| 23.0/23.0 [00:00<00:00, 117kB/s]
(base) xiangzhen@192 starhub-server %

**Comment by SeanHH86** [comment]
done.
