### ISSUE TITLE
在 setup.py 中支持按需下载依赖项

### ISSUE THREAD

**Issue by wei1793786487** [OpenCSGs/csghub-sdk#36]
安装依赖的时候，所有依赖项都会被下载，假设我只需下载上传模型相关的功能的时候，不需要安装torch transfomer等推理相关的依赖

**Comment by SeanHH86** [comment]
@wei1793786487 Good suggestion！已经放到roadmap中了。

**Comment by SeanHH86** [comment]
Fixed.
