### ISSUE TITLE
Download dataset fail via SDK 

### ISSUE THREAD

**Issue by lixjohn** [OpenCSGs/csghub-sdk#53]
step -
1. Open dataset 美国法律案例摘要 download page https://opencsg.com/datasets/MagicAI/BVA_Cases
2. Click downlaod button and copy SDK code
3. Update 'token' and 'cache_dir' field. (Token is from my 'Settings/User Access Token')
4. Excute code, the error reported, please see attachment error.txt
[error.txt](https://github.com/user-attachments/files/17580821/error.txt)
Seems like txt files downloaded successfully but fail when downloading py file https://hub.opencsg.com/hf/datasets/MagicAI/BVA_Cases/resolve/main/attribution/__init__.py, please see snapshot.

<img width="1012" alt="image" src="https://github.com/user-attachments/assets/5341759b-c2a2-4c55-a9bf-5537499bb3bd">

Please notice **Use git download command** 'git clone https://opencsg.com/datasets/MagicAI/BVA_Cases.git', everything goes well. 

BTW - I tried dataset Dataset [历代中医文献数据库](https://opencsg.com/datasets/billionaire/ChineseMedicalBooksCollection) via SDK but failed as well with different error, the error attached here
[error_cmbook.txt](https://github.com/user-attachments/files/17580914/error_cmbook.txt)

**Comment by lixjohn** [comment]
just wondering when will be avaliable on production env? Thanks!

**Comment by SeanHH86** [comment]
It has been fixed. Thanks!

**Comment by SeanHH86** [comment]
Which function do you use in your code? `file_download` for `http_get` ? 
From what I saw `file_download` will create fold <repo_id> under `cache_dir`, and `http_get` downloads file under `cache_dir`.

**Comment by lixjohn** [comment]
Thanks, file a new issue for this. https://github.com/OpenCSGs/csghub-sdk/issues/56
