### ISSUE TITLE
Download folder is different between SDK and Https

### ISSUE THREAD

**Issue by lixjohn** [OpenCSGs/csghub-sdk#56]
Use SDK download dataset [MagicAI/BVA_Cases](https://opencsg.com/datasets/MagicAI/BVA_Cases), SDK will creat folider like this 

<img width="279" alt="image" src="https://github.com/user-attachments/assets/5f6dc4b4-cae2-47bc-a62e-0b7c972775f4">

However, Https download will only create subfolder like this

![image](https://github.com/user-attachments/assets/c1ea05f0-9c5d-42e5-9259-d1152670b2b1)
No MagicAI parent folder, is it by deign or issue? I think SDK behavior makes more sense.

**Comment by lixjohn** [comment]
Here you go
API code. 
    _from pycsghub.snapshot_download import snapshot_download
    token = '**my token**' # token from opencsg.com
    endpoint = "https://hub.opencsg.com"
    repo_type = "dataset"
    repo_id = 'MagicAI/BVA_Cases'
    cache_dir = '**my local folder**' # cache dir of download data
    result = snapshot_download(repo_id, cache_dir=cache_dir, endpoint=endpoint, token=token, repo_type=repo_type)_

https download - 
    _git clone https://opencsg.com/datasets/MagicAI/BVA_Cases.git_

**Comment by SeanHH86** [comment]
Yes, It is by design to create folder like <namespace>/<repo-name> while download model by sdk. Namespace was used to group repo, and have to avoid the same repo-name in one namespace. 

Command `git clone` just focus on one repo.

**Comment by lixjohn** [comment]
thanks for clarification, close this one.
