### ISSUE TITLE
Get package not found error when using sample connect to your CSGHub server code

### ISSUE THREAD

**Issue by lixjohn** [OpenCSGs/csghub-sdk#61]
Run folloing code, copy from README file

    import os 
    from pycsghub.repo_reader import AutoModelForCausalLM, AutoTokenizer
    os.environ['CSG_TOKEN'] = 'my token from setting'
    
    mid = 'OpenCSG/csg-wukong-1B'
    model = AutoModelForCausalLM.from_pretrained(mid)
    tokenizer = AutoTokenizer.from_pretrained(mid)
    
    inputs = tokenizer.encode("Write a short story", return_tensors="pt")
    outputs = model.generate(inputs)
    print('result: ',tokenizer.batch_decode(outputs))_

Got error 
    _PS D:\Python code> & C:/Users/johnx/AppData/Local/Programs/Python/Python312/python.exe d:/models/wukong1b/wukong.py
    C:\Users\johnx\AppData\Local\Programs\Python\Python312\Lib\site-packages\transformers\deepspeed.py:24: FutureWarning: transformers.deepspeed module is deprecated and will be removed in a future version. Please import deepspeed modules directly from transformers.integrations
      warnings.warn(
    Traceback (most recent call last):
      File "d:\models\wukong1b\wukong.py", line 2, in <module>
        from pycsghub.repo_reader import AutoModelForCausalLM, AutoTokenizer
      File "C:\Users\johnx\AppData\Local\Programs\Python\Python312\Lib\site-packages\pycsghub\repo_reader\__init__.py", line 2, in <module>
        from .dataset.huggingface.load import *
      File "C:\Users\johnx\AppData\Local\Programs\Python\Python312\Lib\site-packages\pycsghub\repo_reader\dataset\huggingface\load.py", line 2, in <module>
        import datasets
    ModuleNotFoundError: No module named 'datasets'_

**My env is**
  - OS:Windows 11 家庭中文版
  - Python: Python 3.12.7
  - Transformers:Version: 4.42.0
  - PyTorch:Version: 2.5.1
  - CUDA Support (`python -c "import torch; print(torch.cuda.is_available())"`) : False

**Comment by SeanHH86** [comment]
@lixjohn Can you try command `pip list | grep datasets` to check if package `datasets` was installed successfully?

Looks like package `datasets` is not in your env. 

```
#  pip list | grep datasets
datasets                      2.20.0
```

**Comment by lixjohn** [comment]
thanks, not sure why but I checked and installed datasets. Anyway it works fine. close this issue.
